config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' =>'homes#about'
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/profile_image.rb
class ProfileImage < ApplicationRecord
    attachment :image
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  #ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  #ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only:[:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @books = Book.all
    @book.user_id = current_user.id
    @user = current_user
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def create
    @book= Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path  # 投稿一覧画面へリダイレクト
    flash[:notice] = 'Book was successfully destroyed.'
  end

  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to root_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body) #titleとbodyの内容を渡している
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @showbook = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def create
    # １. データを新規登録するためのインスタンス作成
    user = User.new(user_params)
    # ２. データをデータベースに保存するためのsaveメソッド実行
    if user.save
      redirect_to user_path(user.id)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  private

  def correct_user
     user = User.find(params[:id])
     if current_user != user
       redirect_to books_path(user.id)
     end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profile_image_helper.rb
module ProfileImageHelper
end

app/helpers/profile_images_helper.rb
module ProfileImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
       </ul>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
              <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
              <%= f.text_area :body, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update Book', class: "btn btn-success"%>
          </div>

        <%= link_to "Show", book_path(@book.id) %>
         |
        <%= link_to "Back", books_path %>

        <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
  <div class="row">
    <%= render 'users/info', user: @user %>
     <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
         <table class="table">
           <thead>
             <tr>
               <th></th>
               <th>Title</th>
               <th>Opinion</th>
               <th colspan="3"></th>
             </tr>
           </thead>
           <tbody>
             <% @books.each do |book| %>
             <tr>
               <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
               </td>
               <td>
                 <%= link_to book.title, book_path(book) %>
               </td>
               <td>
                 <%= book.body %>
               </td>
             </tr>
             <% end %>
           </tbody>
         </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/info', user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
          <table class="table">
            <tbody>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br />
                  <%= @user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book) %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @book.user_id == current_user.id %>
                <td>
                  <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
                </td>
                <td>
                  <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
                </td>
              <% end %>
            </tbody>
          </table>
      </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book">
      </i>
      <strong>Bookers</strong>
        !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
  <div class="container">
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book">
          </i>
          <strong>Bookers</strong>
           !!
        </h1>
        <p>In
          <i class="fas fa-book">
          </i>
          <strong>Bookers</strong>
           ,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: "fas fa-home nav-link text-light" do %> Home
                <% end %>
              </li>
              <li>
                <a class="fas fa-users nav-link text-light" href="/users"> Users</a>
              </li>
              <li>
                <a class="fas fa-book-open nav-link text-light" href="/books"> Books</a>
              </li>
              <li>
                <a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a>
              </li>
              <% else %>
              <li>
                <a class="fas fa-home nav-link text-light" href="/"> Home</a>
              </li>
              <li>
                <a class="fas fa-link nav-link text-light" href="/home/about"> About</a>
              </li>
              <li>
                <a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a>
              </li>
              <li>
                <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
  <div class="col-md-3">
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>

     <div class="row">
       <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" do %>
       <% end %>
     </div>

     <%= form_with model: @book, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
        <div class="form-group">
          <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control" %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
  </div>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
    <%= @user.errors.count %>件のエラーが発生しました
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
            <div>
            <%= f.attachment_field :profile_image %>
            </div>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/info', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
        　   <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="container">
    <div class="row">
      <%= render 'users/info', user: @user, book: @book %>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @showbook.each do |book| %>
                <tr>
                  <td>
                    <%= link_to attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                  </td>
                  <td>
                    <%= link_to book.title, book_path(book) %>
                  </td>
                  <td>
                    <%= book.body %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
        </div>
    </div>
  </div>